### ISSUE TITLE
error: failed retrieving file 'dkp-libs.db' from downloads.devkitpro.org : The requested URL returned error: 403

### ISSUE THREAD

**Issue by pkmnsnfrn** [devkitPro/pacman#31]
I am following the instructions from https://devkitpro.org/wiki/devkitPro_pacman.

After running `sudo gdebi devkitpro-pacman.amd64.deb`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading state information... Done

devkitPro package manager
  A lightly customised build of arch pacman used to manage the tools and libraries maintained and distributed by devktPro.
Do you want to install the software package? [y/N]:y
(Reading database ... 110047 files and directories currently installed.)
Preparing to unpack devkitpro-pacman.amd64.deb ...
Unpacking devkitpro-pacman (1.0.2) over (1.0.2) ...
Setting up devkitpro-pacman (1.0.2) ...
==> Appending keys from devkitpro.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 032F4C9D0B8FF3BC84019B7862C7609ADA219C60...
  -> Locally signing key BC26F752D25B92CE272E0F44F7FD5492264BB9D0...
==> Importing owner trust values...
==> Updating trust database...
gpg: no need for a trustdb check
:: Synchronizing package databases...
error: failed retrieving file 'dkp-libs.db' from downloads.devkitpro.org : The requested URL returned error: 403
error: failed to update dkp-libs (unexpected error)
error: failed retrieving file 'dkp-linux.db' from downloads.devkitpro.org : The requested URL returned error: 403
error: failed to update dkp-linux (unexpected error)
error: failed to synchronize all databases
dpkg: error processing package devkitpro-pacman (--install):
 installed devkitpro-pacman package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 devkitpro-pacman
```

`cat /proc/version` returns
```
Linux version 5.11.0-1017-gcp (buildd@lgw01-amd64-056) (gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0, GNU ld (GNU Binutils for Ubuntu) 2.36.1) #19-Ubuntu SMP Thu Aug 12 01:22:45 UTC 2021
```

and lsb_release -a returns
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```

Google leads to https://github.com/devkitPro/pacman/issues/22#issue-653659360, but I am not using a CI workflow (I'm not super familiar with the concept, but a cursory glance of wikipedia tells me this is not what i'm doing). Am I doing something wrong, or is something broken on server side? Thanks!

**Comment by alkaris2** [comment]
I get this same issue but on Arch Linux. Status 403 is returned on download.

**Comment by cornixsenex** [comment]
Was any fix found for this issue? I'm having it right now 
error: failed retrieving file 'dkp-libs.db' from downloads.devkitpro.org : The requested URL returned error: 403

**Comment by pkmnsnfrn** [comment]
Unfortunately no, I gave up and moved onto a different solution.

**Comment by cornixsenex** [comment]
It's very strange that this had been working for me for around a year and only this morning started occuring
Thanks for the input, I'll look at removing the devkitPro repo I suppose

**Comment by cornixsenex** [comment]
Actually it has started working again...I'm going to assume it was a server downtime issue

**Comment by pkmnsnfrn** [comment]
Interesting, perhaps I should try again then. Thanks for the update!

**Comment by WinterMute** [comment]
403 is permission denied. It could be anything from your ISP's "parental controls" to doing something that's triggered filters.  Depending on how much abuse and harassment I've been subjected to recently it might be possible to convince me to look & see if you've triggered a ban and whether or not it might be unfortunate collateral damage.

**Comment by pkmnsnfrn** [comment]
The machine in question is a remote machine (a Windows 365 cloud PC to be
exact) so it could either be collateral damage or Microsoft's ISP... Oh
well. Happy to try to help investigate if need be.

**Comment by robrichardson13** [comment]
Hey @pkmnsnfrn I was able to solve this in a little bit of a weird method, but worked for my use case.

I too am using a Windows VM (via AWS) and am getting the 403 error when trying to run specific `pacman` commands. In order to work around this I setup a local proxy to tunnel traffic from the VM to my local machine (which is able to access `pkg.devkitpro.org` successfully.)

I setup a tunnel using [Ngrok](https://ngrok.com/). This allows you to open up a local port to a public URL.

I created a very simple [Express](https://expressjs.com/) app with [express-http-proxy](https://www.npmjs.com/package/express-http-proxy) to proxy requests to the correct site.

**Full example here:**
1. Made a new directory with `mkdir proxy`
2. `cd proxy`
3. `vim app.js` or any method to create the file
4. `npm init -y`
5. `npm install express` to install express
6. `npm install express-http-proxy` to install `express-http-proxy`
7. Inside `app.js`
```
const express = require('express')
const app = express()
const port = 3000

var proxy = require('express-http-proxy');

app.use('/', proxy('https://pkg.devkitpro.org'));

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})
```

8. Serve up the proxy with `node app.js`
9. Open up the tunnel with `ngrok http 3000`
10. After this runs you'll get a new ngrok URL to point traffic to (see below where to put this)

Then inside the Windows VM lets update the packages URL to point to our new proxy.
1. Navigate to `C:\devkitPro\msys2\etc`
2. Open up `pacman.conf` and scroll to the bottom where you see `dkp-libs` and `dkp-windows`
3. Replace `Server = https://pkg.devkitpro.org/packages` with your new ngrok URL like `Server = https://xxxx-xxxx-xxxx.ngrok.io/packages`
4. Replace `Server = https://pkg.devkitpro.org/packages/windows/$arch` with your new ngrok URL like `Server = https://xxxx-xxxx-xxxx.ngrok.io/packages/windows/$arch`
5. Save the file and try tunning your `pacman` commands again.

If everything was setup correctly, you'll be sending traffic to the ngrok URL which would redirect the traffic to your local express app, which would then redirect the traffic to the official `pkg.devkitpro.org` repository.

**Comment by WinterMute** [comment]
In some cases people are getting banned because, for some ridiculous reason, they feel it necessary to run a script checking for updates several hundred times a day. This has a negative impact on other users so, if you're running a cron script to run `dkp-pacman -Syu' more than once a day then please stop.

In other cases people are using pacman to install every single binary we provide for every single commit they make as part of their CI. Please don't do this either. This has led to banning of CI infrastructure which has impacted on Windows 365 cloud PC. We provide docker images for CI purposes, please use those. https://hub.docker.com/u/devkitpro

Other users are just leeching everything we do and hosting our binaries elsewhere despite being asked not to. Not only that but they are providing instructions to use their binaries in preference to our CI in a way that is incompatible with our infrastructure purely in order to not update their projects to work with our stock tools. This causes massive support issues for us and mires users who follow their instructions in technical debt that is incredibly difficult to dig them out of.

Unfortunately this means that some innocent users may have ended up banned which we regret. It may be possible, as I've said, to get some bans lifted but bear in mind that we have no way to tell if you are genuinely innocent or a user who wants to get unbanned in order to carry on one of the problematic activities listed above.

**Comment by Istador** [comment]
> In other cases people are using pacman to install every single binary we provide for every single commit they make as part of their CI. Please don't do this either. This has led to banning of CI infrastructure which has impacted on Windows 365 cloud PC. We provide docker images for CI purposes, please use those. https://hub.docker.com/u/devkitpro

Please make this more prominent.
E.g. on the wiki page that is [linked](https://devkitpro.org/wiki/devkitPro_pacman) in the issue description and/or on the [Getting Started](https://devkitpro.org/wiki/Getting_Started) page.
As far as I see the only mentioning of the docker registry on the wiki is on the [About](https://devkitpro.org/wiki/About) page that no one's gonna read.

**Comment by WillSams** [comment]
> In some cases people are getting banned because, for some ridiculous reason, they feel it necessary to run a script checking for updates several hundred times a day. This has a negative impact on other users so, if you're running a cron script to run `dkp-pacman -Syu' more than once a day then please stop.
> 
> In other cases people are using pacman to install every single binary we provide for every single commit they make as part of their CI. Please don't do this either. This has led to banning of CI infrastructure which has impacted on Windows 365 cloud PC. We provide docker images for CI purposes, please use those. https://hub.docker.com/u/devkitpro
> 
> Other users are just leeching everything we do and hosting our binaries elsewhere despite being asked not to. Not only that but they are providing instructions to use their binaries in preference to our CI in a way that is incompatible with our infrastructure purely in order to not update their projects to work with our stock tools. This causes massive support issues for us and mires users who follow their instructions in technical debt that is incredibly difficult to dig them out of.
> 
> Unfortunately this means that some innocent users may have ended up banned which we regret. It may be possible, as I've said, to get some bans lifted but bear in mind that we have no way to tell if you are genuinely innocent or a user who wants to get unbanned in order to carry on one of the problematic activities listed above.

You could have just mentioned the Docker images for CI purposes, the rest of that was just a lot of unnecessary reading.  And hen squabbling.

**Comment by john-peterson** [comment]
I am on my phone on expedition and always use gcloud as a second hand. In docker I have no GitHub credentials or anything and the shell is unusable it's not my computer .  my gcloud is like my desktop shell my own computer . in docker nothing works I can't sync my files or use git hub I am not copying sensitive credentials to another shell just because I need to build Nintendo apps 

~~~
sudo docker run -it devkitpro/devkitarm bash
gh
bash: gh: command not found
gsutil rsync
bash: gsutil: command not found
~~~

 # provide binary zip install path 

I don't find any binary zip links

https://devkitpro.org/wiki/Getting_Started

or some way to mirror your pack man server. I am now trying to SCP the installation from docker that is nested inside another gcloud shell. seems like complete insanity 


 # un block Finland IP range  

can you unblock Finland 34.88.x.x google cloud platform gcloud. or remove the IP range ban and treat all IP on individual basis . very few use devkitpro and my particular Google IP would not have ever accessed your server before but you blocked the entire range

this range seems to only belong to Google Finland maybe you can trial it and see if they still abuse you. computer crime is very low in Finland and other rich countries probably no one will abuse it enough to require an IP range ban the individual quota should be enough the same as on my DNA cellular connection  

~~~
sudo bash install-devkitpro-pacman |& tee log
error: failed retrieving file 'dkp-libs.db' from pkg.devkitpro.org : The requested URL returned error: 403

ipinfo-cli --ip 34.88.1.1|nocolor|copy
IP Address: 34.88.1.1
City: Lappeenranta
Region: South Karelia
Country: FI
Location: 61.0587,28.1887
Postal: 53100
Timezone: Europe/Helsinki
~~~

**Comment by forsureitsme** [comment]
It should at least be mentioned once in https://devkitpro.org/wiki/devkitPro_pacman that there is an alternative method of installation with docker in workstations, since the current installation process for the Unix-like systems is broken due to pkg.devkitpro.org always returning 403 for the databases.

**Comment by luluco250** [comment]
Randomly got hit by this while upgrading my Arch system, I only use devkitpro for compiling homebrew for my Switch so I'll just turn off its repositories until it's fixed.

Not using a VPN, Brazilian IP, so no idea why I'm getting 403.

**Comment by WinterMute** [comment]
Please don't comment on closed issues. Brazilian IPs are currently impacted by bots sending millions of requests from Brazilian residential IPs, there is very little we can do to resolve this.
